### ISSUE TITLE
the generated CAD and sk directories are empty

### ISSUE THREAD

**Issue by PPzpower** [BunnySoCrazy/SECAD-Net#5]
Hello, I'm delighted to have the opportunity to learn from your expertise. I have a question: I followed your script and executed the code, but the generated CAD and sk directories are empty. What could be the reason for this

**Comment by CurryXing30** [comment]
Hello I have also encountered the problem that the generated CAD and sk directories are empty. Have you solved it ? Hope to get your valuable advice
