### ISSUE TITLE
folder and file not found

### ISSUE THREAD

**Issue by Chunan-Yu** [BunnySoCrazy/SECAD-Net#8]
Thank you for the great work. When I followed the readme you provided and ran it step by step, I found that the scripts folder and specs.json file could not be found.

**Comment by YCA-eng** [comment]
The specs.json is in https://github.com/FENGGENYU/CAPRI-Net/blob/main/abc_voxel/specs.json

**Comment by gaoqy99** [comment]
hi，
I have encountered the same problem as you，Could you please let me know if you have resolved this issue?
